setwd("~/Google Drive/2016 1Spring/Machine Learning/ML Project")
library(data.table)
library(plyr)
vars <- c('Physician_Profile_ID','Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID','Total_Amount_of_Payment_USDollars','Date_of_Payment','Program_Year')
data <- fread('../ML Project Data/CMS/PGYR14_P011516/OP_DTL_GNRL_PGYR2014_P01152016.csv', sep=',', header=TRUE, select = vars, colClasses = 'character',verbose=FALSE,showProgress=FALSE)
data <- rbind(data,fread('../ML Project Data/CMS/PGYR13_P011516/OP_DTL_GNRL_PGYR2013_P01152016.csv', sep=',', header=TRUE, select = vars, colClasses = 'character',verbose=FALSE,showProgress=FALSE))
data <- subset(data, Physician_Profile_ID != '')
names(data) <- c('Physician_ID','Payer_ID','USD','Date','Year')
data$USD <- as.numeric(data$USD)
data <- ddply(data,.(Physician_ID,Payer_ID,Year), summarise, USD = sum(USD))
write.csv(data,file='Ana Files/Clean Data/payments_CMS.csv',row.names=FALSE)
